version: '3.4'

services:
  portfolio:
    image: sesan07/portfolio
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
      - DIRECTUS_URL=${PORTFOLIO_DIRECTUS_URL}
      - UPDATE_INTERVAL=${PORTFOLIO_UPDATE_INTERVAL}
    ports:
      - 4000:4000
